spring:
  jpa:
    show-sql: true
    properties:
      format_sql: true
      hibernate:
        ddl-auto: validate
      database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3307/delivery?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1217

server:
  port: 8081